name: CustomCrafting
authors: [ WolfyScript ]
main: me.wolfyscript.customcrafting.CustomCrafting
version: 1.6.6.0
api-version: "1.14"
depend: [ WolfyUtilities ]
softdepend: [ MythicMobs, Oraxen, ItemsAdder, PlaceholderAPI ]
description: Create your own custom recipes for workbenches and furnaces. Disable Vanilla recipes and more.